### ISSUE TITLE
Dots indicator initialises with the wrong number of dots initially

### ISSUE THREAD

**Issue by createS0ftware** [tommybuonomo/dotsindicator#20]
I have 2 items in my viewpager and the dots indicator initialises with 3 dots

I can't see why - but if is set the viewpager to the second page then it initialises with 2 dots.

i think the problem is that in refreshDots() you call buildDot which adds a child view (dot) to the layout - if dotIndicatorView is not initialised.

You need to remove this view after you find that the viewpager adapter has pages - in that same refreshDots() method

**Comment by createS0ftware** [comment]
Hmmm.. i just checked the code again - looks like i have a different version than what is in the maven rep...

**Comment by GalatiaPar** [comment]
This problem is also existent on the WormDotsIndicator. Any updates on this?

**Comment by tommybuonomo** [comment]
Hello @createS0ftware and @GalatiaPar,

I can't reproduce the bug of the three dots instead of two.

Does the new release **3.0.2** fix the issue ?

**Comment by GalatiaPar** [comment]
Hi @tommybuonomo . Not really. 

I can see a different issue arising depending on the case:
- Set up the view pager on the WormDotsIndicator as soon as you retrieve the list info you want to swipe through and list is empty. In this case it shows only one dot (can provide video)
- Setup the view pager on the WormDotsIndicator, if and only if I have a non-empty list, in which case I when the containers of the list are 2, I get 3 dots instead of 2. The first dot seems to be excess, as it goes away on the first swipe I do.

**Comment by tommybuonomo** [comment]
@GalatiaPar can you check now with **3.0.3** please ?

**Comment by createS0ftware** [comment]
I'll check it in the next few hours

**Comment by createS0ftware** [comment]
Fixed !! Well done !! Thanks !!

**Comment by bhaskarraj** [comment]
I am still facing the same problem with the wrong number of dots in 3.0.3
